#!/bin/sh
# sign-file algo key cert module

store="sql:${3%/cert9.db}"

trap 'rm -f "$sig"' EXIT INT
sig="$(mktemp)"

p7sign -d "$store" -a "$1" -u 6 -k "$2" < "$4" > "$sig" &&
  "/usr/lib/linux-kbuild-${kernelver%.*}/scripts/sign-file" -s "$sig" "$1" /ENOENT "$4"
