#!/bin/sh
# sign-file algo key cert module

store="sql:${3%/cert9.db}"

trap 'rm -f "$sig"' EXIT INT
sig="$(mktemp)"

p7alg="$1"
case "$p7alg" in
	sha256)	p7alg=SHA-256 ;;
esac

signfile=
for suff in "$kernelver" "${kernelver%-*}" "${kernelver%.*}"; do
	[ -x "/usr/lib/linux-kbuild-$suff/scripts/sign-file" ] &&
		signfile="/usr/lib/linux-kbuild-$suff/scripts/sign-file" &&
		break
done
[ -n "$signfile" ] || { echo "No sign-file!"; exit 1; }

p7sign -d "$store" -a "$p7alg" -u 6 -k "$2" < "$4" > "$sig" &&
  "$signfile" -s "$sig" "$1" /ENOENT "$4"
